/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment1SOFT2412;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // menu is not work with APP
        Process process = new Process();
        process.process();
    }
}
